### ISSUE TITLE
grow/etch method: "into", "through" and "on" do not work with empty input

### ISSUE THREAD

**Issue by klayoutmatthias** [klayoutmatthias/xsection#1]
If the argument to "into", "through" and "on" is empty, the following message will be issued:

```
ERROR: Ambiguous overload variants - multiple method declarations match arguments in Edges::initialize
```

Reason: the ```RBA::Edges``` constructor is not able to resolve the overload when an empty array is passed.

**Comment by nique-pal** [comment]
hi Matthias, I have been getting the "ERROR: Ambiguous overload ..." popup when I try to xsection in certain parts of the layout. To make my script robust, I attempted to included 'if' statements before each grow/etch statement to check if arrays passed to grow/etch are empty. However, I still get the "ERROR: Ambiguous overload ..." popup. What are your thoughts to overcome this issue? Thank you.

**Comment by nique-pal** [comment]
hi Matthias, I was able to resolve the above issue. In my script, layer1 was grown into the wafer. layer2 was grown on top of layer1. If for the chosen region, no layer1 was grown, layer2 was trying to grow over nothing. To alleviate this issue, I put in an 'if' statement:

if(@layer1 != nil)
   layer2 = grow(1,1,:on=>layer1,:mode => :round)
end

additionally, i am setting all deposition layers to 0 at the beginning of my script by using:
layer1 = deposit(0)
layer2 = deposit(0) etc.

Setting all layers to 0 ensures that I am not carrying over any objects from a previous simulation run.
