### ISSUE TITLE
Deposit problems with topology beneath

### ISSUE THREAD

**Issue by Tom7Kimi** [klayoutmatthias/xsection#11]
With the new version of xsection we face problems with the deposit function on topography. We get the following error message: 
std::bad_alloc in Region::merge

Should we avoid deposit later in the code? 

With the old xsection it works fine.

Thank you very much!

**Comment by klayoutmatthias** [comment]
The problem was the complexity of "rounded topology on rounded". The solution is to simplify the computation. See attachement for a sketch.
[xsection.zip](https://github.com/klayoutmatthias/xsection/files/2254395/xsection.zip)

**Comment by klayoutmatthias** [comment]
The fix is ready and will be released with version 1.3
