### ISSUE TITLE
Wish: Implement an additional mode ":downto" for the etch method

### ISSUE THREAD

**Issue by Tom7Kimi** [klayoutmatthias/xsection#14]
Sometimes it would be helpful to use a stopping layer for etching. Something like ":downto" for the planarize method.
An example would be a layer which is covered inside another layer, like a metal inside oxid. If you want to etch now a contact, depending on the topology the contact could go through the metal, because in the etch method the mode :into => oxid was used. A workaround for the moment is to etch it in two steps.
Not an urgent topic, only nice to have :)
Thanks a lot for this amazing tool!

**Comment by klayoutmatthias** [comment]
I'm currently doing some maintenance of this package ... sorry for the late response.

Actually "planarise" is somewhat fake - ":downto" is only a way to determine the stop position by some material. It's not local: a single peak somewhere makes the planarisation stop at this level. For "planarise" this might be acceptable, but to simulate an etch stop, a non-local operation is likely not the thing you like. 

I think splitting into steps is the best approximation you can get now. This is one of the weaknesses of the geometry-based approach.

**Comment by Tom7Kimi** [comment]
Hy Matthias! Many thanks for your support! I will split the steps. :)
Have a nice evening!
Topic can be closed
