### ISSUE TITLE
fail to load on package manager, version ID in salt file is 1.7 i.o. 1.8?

### ISSUE THREAD

**Issue by ydufour-xfab** [klayoutmatthias/xsection#33]
Symptom: failure to update in package manager
Suggestion:
  File: master/src/grain.xml
   Version info is 1.7
  should be 1.8?

I downloaded, fixed my own copy and loaded by hand.

**Comment by klayoutmatthias** [comment]
Thanks for reporting this problem.

I have just release version 1.9 which should report properly as 1.9.

Matthias

**Comment by ydufour-xfab** [comment]
Thank you for your support and for the fantastic Xsection tool.
Yves
