### ISSUE TITLE
Etch only lateral not longer available?

### ISSUE THREAD

**Issue by Tom7Kimi** [klayoutmatthias/xsection#8]
With the new version of xsection I face an issue with lateral etching. It seems that it is not longer possible to create only a lateral etching. 
For example: etch(0.0, 0.2, :into => material) does not work any more.

The error message to this topic:
Internal error: ../../../src/db/db/dbPolygonTools.cc:1741 cmin != cf && cmax != cf was not true in Polygon::minkowsky_sum
 
Thanks for your help!

**Comment by klayoutmatthias** [comment]
It easy to reproduce - I have added two files for a testcase.

[xsection_8.zip](https://github.com/klayoutmatthias/xsection/files/2246168/xsection_8.zip)

Thanks for reporting the issue.

Matthias

**Comment by klayoutmatthias** [comment]
The fix will be released with version 1.3
